###########
# General #
###########
name: 'Divi'
description: 'Website desc.'
url: 'http://yourdomain.io'
email: ''
phone: ''

###############
# Divi config #
###############

# Header mode : default, center or vertical
header_type: 'default'
# Boxed layout : true or false
boxed_layout: false
# Logo url : url
logo_url: false

##########
# Social #
##########
facebook_url: ''
twitter_url: ''
google_url: ''