###########
# General #
###########
baseurl: '/divi/'
name: 'Divi'
description: 'Website desc.'
url: 'http://yourdomain.io'
#email: ''
#phone: ''

###############
# Divi config #
###############

# Header mode : default, center or vertical
header_type: 'default'
# Boxed layout : true or false
boxed_layout: false
# Logo url : url (if not is set load default logo /assets/img/logo.png)
#logo_url: ''

##########
# Social #
##########
#facebook_url: ''
#twitter_url: ''
#google_url: ''