###########
# General #
###########
name: 'Divi'
description: 'Website desc.'
url: 'http://yourdomain.io'


###############
# Divi config #
###############

# Header mode : default, center or vertical
header_type: 'default'
# Boxed layout : true or false
boxed_layout: true